# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20171016_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='can_delete',
        ),
    ]
