# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_auto_20171019_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_changed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_changed',
        ),
    ]
