# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20171019_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(related_name='_profile_followees_+', to='grumblr.Post'),
        ),
    ]
