# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_post_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
