# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0011_auto_20180414_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
