# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20180414_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='searching',
            field=models.ManyToManyField(related_name='_profile_searching_+', to='grumblr.Post'),
        ),
    ]
