# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_profile_searching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='searching',
        ),
        migrations.AddField(
            model_name='profile',
            name='searching_following',
            field=models.ManyToManyField(related_name='_profile_searching_following_+', to='grumblr.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='searching_not_following',
            field=models.ManyToManyField(related_name='_profile_searching_not_following_+', to='grumblr.Post'),
        ),
    ]
